//! Properties of `npm_utils::minimatch`, generated by proptest over the grammar in
//! `common/glob_grammar.rs`: what must hold for every pattern, with a path each pattern matches
//! where the grammar knows its language. `PROPTEST_CASES` sets the cases per property (256 by
//! default; the pack-e2e job runs 4096), and a failing case is written to
//! `proptest-regressions/` and replayed first on the next run.

#[allow(dead_code)]
mod common;

use common::glob_grammar::{self as glob, Grammar};
use npm_utils::minimatch::{brace_expand, escape, unescape, Error, Minimatch, Options};
use proptest::prelude::*;
use proptest::test_runner::Config;

const STRICT: Options = Options {
    quirks: false,
    ..Options::DEFAULT
};

fn config() -> Config {
    Config {
        max_shrink_iters: 2000,
        max_shrink_time: 60_000,
        ..Config::default()
    }
}

/// A hang or an abort is a failing case: the timeout runs the test in a forked process.
fn forked() -> Config {
    let mut config = config();
    if config.timeout == 0 {
        config.timeout = 20_000;
    }
    config
}

fn mode(strict: bool) -> Options {
    if strict {
        STRICT
    } else {
        Options::DEFAULT
    }
}

proptest! {
    #![proptest_config(forked())]

    /// Every pattern compiles or fails by name within the timeout: the grammar, symbol soup,
    /// arbitrary text and the shapes that amplify a cost past its budget.
    #[test]
    fn new_terminates_on_any_pattern(
        pattern in prop_oneof![
            glob::pattern(Grammar::FULL).prop_map(|p| p.render()),
            glob::raw_pattern(),
            glob::bomb(),
        ],
        strict in any::<bool>(),
    ) {
        let _ = Minimatch::new(&pattern, mode(strict));
    }
}

proptest! {
    #![proptest_config(config())]

    /// A grammar pattern never reaches the regex engine's own refusals: every source the port
    /// emits for syntax it accepts compiles.
    #[test]
    fn grammar_patterns_never_hit_the_engine(p in glob::pattern(Grammar::FULL), strict in any::<bool>()) {
        if let Err(e) = Minimatch::new(&p.render(), mode(strict)) {
            prop_assert!(!matches!(e, Error::Regex { .. }), "{e}");
        }
    }

    #[test]
    fn match_never_panics(pattern in glob::raw_pattern(), path in glob::arbitrary_path(), options in glob::preset()) {
        if let Ok(mm) = Minimatch::new(&pattern, options) {
            let _ = mm.is_match(&path);
            let _ = mm.is_match_partial(&path);
        }
    }

    /// The oracle: a path drawn from the pattern's language matches it, in both modes, with
    /// and without `dot`.
    #[test]
    fn an_instantiated_path_matches_its_pattern(
        (p, path) in glob::pattern_with_path(Grammar::ORACLE),
        dot in any::<bool>(),
        strict in any::<bool>(),
    ) {
        let pattern = p.render();
        let options = Options { dot, ..mode(strict) };
        // A pattern past a budget is a named outcome of the design, not an answer; proptest
        // fails the run when too many cases are rejected this way.
        let mm = match Minimatch::new(&pattern, options) {
            Ok(mm) => mm,
            Err(Error::Nodes { .. } | Error::Braces { .. }) => {
                return Err(TestCaseError::reject("compile budget"))
            }
            Err(e) => return Err(TestCaseError::fail(e.to_string())),
        };
        let hit = match mm.is_match(&path) {
            Ok(hit) => hit,
            // The step budget is a named outcome of the design, reachable by nested negations
            // under repeats against short names; such a case says nothing about the answer, and
            // proptest fails the run when too many cases are rejected this way.
            Err(Error::Steps { .. }) => return Err(TestCaseError::reject("step budget")),
            Err(e) => return Err(TestCaseError::fail(e.to_string())),
        };
        prop_assert!(hit, "{pattern:?} must match {path:?}");
    }

    #[test]
    fn escape_round_trips(s in "\\PC{0,24}", magical_braces in any::<bool>()) {
        prop_assert_eq!(unescape(&escape(&s, magical_braces), magical_braces), s);
    }

    /// An escaped text is a literal pattern that matches the text and nothing magic remains.
    #[test]
    fn an_escaped_literal_matches_itself(s in "[a-c.*?\\[\\](){}|\\\\!#é/ ]{0,12}") {
        let literal = Options { nonegate: true, nocomment: true, ..Options::DEFAULT };
        // minimatch's own `escape` does not survive its brace expansion: a `{…}` pair in the text
        // makes the quirks reading strip the escapes again (`braces-strip-escapes`), and
        // minimatch 10.2.5 answers false for such a text too. Strict mode keeps the escapes.
        let brace_pair = s.find('{').is_some_and(|i| s[i..].contains('}'));
        // minimatch's level-one optimization drops a segment and the `..` after it (`a/..`
        // reads as the empty pattern), so a text with a `..` segment has no literal pattern.
        prop_assume!(!s.split('/').any(|segment| segment == ".."));
        for options in [literal, Options { quirks: false, ..literal }] {
            if options.quirks && brace_pair {
                continue;
            }
            let mm = Minimatch::new(&escape(&s, true), options).map_err(|e| TestCaseError::fail(e.to_string()))?;
            prop_assert!(!mm.has_magic(), "{:?} has magic", escape(&s, true));
            prop_assert!(mm.is_match(&s).unwrap(), "{:?} must match {s:?}", escape(&s, true));
        }
    }

    /// `!p` matches exactly the paths `p` does not; `flip_negate` makes `!p` answer like `p`.
    #[test]
    fn a_leading_bang_is_the_complement(
        p in glob::pattern(Grammar { negate: false, comments: false, ..Grammar::FULL }),
        path in glob::arbitrary_path(),
    ) {
        let pattern = p.render();
        prop_assume!(!pattern.starts_with('!'));
        let negated = format!("!{pattern}");
        let (Ok(plain), Ok(bang)) = (Minimatch::new(&pattern, Options::DEFAULT), Minimatch::new(&negated, Options::DEFAULT)) else {
            return Ok(());
        };
        let flipped = Minimatch::new(&negated, Options { flip_negate: true, ..Options::DEFAULT }).unwrap();
        if let (Ok(a), Ok(b), Ok(c)) = (plain.is_match(&path), bang.is_match(&path), flipped.is_match(&path)) {
            prop_assert_eq!(a, !b, "{:?} and {:?} against {:?}", pattern, negated, path);
            prop_assert_eq!(a, c, "{:?} and flipped {:?} against {:?}", pattern, negated, path);
        }
    }

    /// A pattern matches a path exactly when one of its brace expansions does.
    #[test]
    fn brace_expansion_distributes_over_matching(
        p in glob::pattern(Grammar { negate: false, comments: false, ..Grammar::FULL }),
        path in glob::arbitrary_path(),
    ) {
        let pattern = p.render();
        prop_assume!(!pattern.starts_with('!'));
        let Ok(whole) = Minimatch::new(&pattern, Options::DEFAULT) else { return Ok(()) };
        let Ok(hit) = whole.is_match(&path) else { return Ok(()) };
        let nobrace = Options { nobrace: true, ..Options::DEFAULT };
        let mut any = false;
        for expansion in brace_expand(&pattern, Options::DEFAULT).unwrap() {
            let one = Minimatch::new(&expansion, nobrace).map_err(|e| TestCaseError::fail(e.to_string()))?;
            any |= one.is_match(&path).map_err(|e| TestCaseError::fail(e.to_string()))?;
        }
        prop_assert_eq!(hit, any, "{:?} against {:?}", pattern, path);
    }

    /// `nocase` and `dot` only add matches; a full match is a partial match.
    #[test]
    fn nocase_dot_and_partial_only_add_matches(
        p in glob::pattern(Grammar { negate: false, comments: false, ..Grammar::FULL }),
        path in glob::arbitrary_path(),
    ) {
        let pattern = p.render();
        prop_assume!(!pattern.starts_with('!'));
        let Ok(base) = Minimatch::new(&pattern, Options::DEFAULT) else { return Ok(()) };
        let Ok(true) = base.is_match(&path) else { return Ok(()) };
        // A negated class or group folds case the other way: `[![:upper:]]` matches `a` and
        // `@(!(a))` matches `A` until `nocase` folds the two cases together, in minimatch as
        // here, so the complement shrinks.
        let widening = if pattern.contains("[!") || pattern.contains("[^") || pattern.contains("!(")
        {
            vec![Options { dot: true, ..Options::DEFAULT }]
        } else {
            vec![Options { nocase: true, ..Options::DEFAULT }, Options { dot: true, ..Options::DEFAULT }]
        };
        for options in widening {
            let wider = Minimatch::new(&pattern, options).unwrap();
            prop_assert!(wider.is_match(&path).unwrap(), "{pattern:?} matched {path:?} by default but not under {options:?}");
        }
        // minimatch answers `**/?(a)*` against `.` true in full mode and false in partial mode,
        // and the port follows it, so the partial half holds for the patterns without `**`.
        if !pattern.contains("**") {
            prop_assert!(base.is_match_partial(&path).unwrap(), "{pattern:?} matched {path:?} fully but not partially");
        }
    }

    /// `matchBase` matches a slash-free pattern against the basename.
    #[test]
    fn match_base_is_the_basename(
        p in glob::pattern(Grammar { max_segments: 1, globstar: false, negate: false, comments: false, trailing_slash: false, ..Grammar::FULL }),
        path in glob::arbitrary_path(),
    ) {
        let pattern = p.render();
        prop_assume!(!pattern.starts_with('!'));
        let Ok(plain) = Minimatch::new(&pattern, Options::DEFAULT) else { return Ok(()) };
        let based = Minimatch::new(&pattern, Options { match_base: true, ..Options::DEFAULT }).unwrap();
        let basename = path.rsplit('/').find(|s| !s.is_empty()).unwrap_or("");
        if let (Ok(a), Ok(b)) = (based.is_match(&path), plain.is_match(basename)) {
            prop_assert_eq!(a, b, "{:?} against {:?} (basename {:?})", pattern, path, basename);
        }
    }

    /// Runs of slashes in a path coalesce, as `slashSplit` reads them. The path is two drawn
    /// paths joined by a slash, so there is always one to double and no case is rejected.
    #[test]
    fn slash_runs_coalesce(
        p in glob::pattern(Grammar::FULL),
        (head, tail) in (glob::arbitrary_path(), glob::arbitrary_path()),
        at in any::<prop::sample::Index>(),
    ) {
        let path = format!("{head}/{tail}");
        let slashes: Vec<usize> = path.match_indices('/').map(|(i, _)| i).collect();
        let Ok(mm) = Minimatch::new(&p.render(), Options::DEFAULT) else { return Ok(()) };
        let mut doubled = path.clone();
        doubled.insert(slashes[at.index(slashes.len())], '/');
        if let (Ok(a), Ok(b)) = (mm.is_match(&path), mm.is_match(&doubled)) {
            prop_assert_eq!(a, b, "{:?} against {:?} and {:?}", p.render(), path, doubled);
        }
    }

    /// Every error but the length one quotes the pattern first, so a caller matching many
    /// rules can report the one at fault as is.
    #[test]
    fn errors_quote_the_pattern_first(pattern in prop_oneof![glob::raw_pattern(), glob::bomb()], strict in any::<bool>()) {
        if let Err(e) = Minimatch::new(&pattern, mode(strict)) {
            if !matches!(e, Error::PatternTooLong { .. }) {
                prop_assert!(e.to_string().starts_with(&format!("{pattern:?}: ")), "{e}");
            }
        }
    }

    /// Ordinary rules read the same in both modes: the promise docs/pack.md makes.
    #[test]
    fn strict_agrees_with_quirks_on_quirk_free_patterns(p in glob::pattern(Grammar::QUIRK_FREE), path in glob::arbitrary_path()) {
        let pattern = p.render();
        // A leading `!(` is the one quirk the grammar can still spell, through a negated pattern
        // or a negation group first.
        prop_assume!(!pattern.trim_start_matches('!').starts_with('('));
        match (Minimatch::new(&pattern, Options::DEFAULT), Minimatch::new(&pattern, STRICT)) {
            (Ok(quirks), Ok(strict)) => {
                if let (Ok(a), Ok(b)) = (quirks.is_match(&path), strict.is_match(&path)) {
                    prop_assert_eq!(a, b, "{:?} against {:?}", pattern, path);
                }
            }
            (Err(a), Err(b)) => prop_assert_eq!(a.to_string(), b.to_string()),
            (quirks, strict) => prop_assert!(false, "{pattern:?}: quirks {quirks:?}, strict {strict:?}"),
        }
    }

    /// The raw-extension fast path (quirks mode) answers like the regex it stands in for,
    /// escapes aside.
    #[test]
    fn the_raw_extension_fast_path_agrees_with_the_regex(
        ext in "[a-cA-C.é]{1,4}",
        name in "[a-cA-C.é]{0,6}",
        dot in any::<bool>(),
        nocase in any::<bool>(),
    ) {
        // minimatch's fast path takes `.` and `..` under `dot`, its regex never does; the port
        // follows each in its mode.
        prop_assume!(name != "." && name != "..");
        let pattern = format!("*{ext}");
        let quirks = Minimatch::new(&pattern, Options { dot, nocase, ..Options::DEFAULT }).unwrap();
        let strict = Minimatch::new(&pattern, Options { dot, nocase, ..STRICT }).unwrap();
        prop_assert_eq!(quirks.is_match(&name).unwrap(), strict.is_match(&name).unwrap(), "{:?} against {:?}", pattern, name);
    }

    /// A budget raised never turns an accepted pattern into an error.
    #[test]
    fn raising_a_budget_never_turns_ok_into_err(pattern in prop_oneof![glob::pattern(Grammar::FULL).prop_map(|p| p.render()), glob::bomb()]) {
        let base = Options::DEFAULT;
        if Minimatch::new(&pattern, base).is_ok() {
            let raised = Options {
                max_extglob_nodes: base.max_extglob_nodes * 2,
                max_extglob_nesting: base.max_extglob_nesting * 2,
                max_brace_expansions: base.max_brace_expansions * 2,
                max_brace_groups: base.max_brace_groups * 2,
                ..base
            };
            prop_assert!(Minimatch::new(&pattern, raised).is_ok(), "{pattern:?} fails with raised budgets");
        }
    }
}
